<?php // $Id$

/**
*  @file
*  Provides integration between the CAPTCHA module [http://drupal.org/project/captcha]
*  and the text-only CAPTCHA service textcaptcha.com
*/

/**
*  Implementation of hook_menu()
*/
function textcaptcha_menu() {
  $items = array();
    $items['admin/user/captcha/textcaptcha'] = array(
      'title' => 'Text CAPTCHA',
      'description' => 'Builds CAPTCHAs that use text rather than images.',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('textcaptcha_settings_form'),
      'access arguments' => array('administer CAPTCHA settings'),
      'type' => MENU_LOCAL_TASK
    );
  return $items;
}

/**
*  Admin settings form callback
*/
function textcaptcha_settings_form() {
  $form = array();
  
  $form['instructions']['#value'] = t('To use TextCAPTCHA, you need to get an API key by !link', 
                      array('!link' => l('registering at textcaptcha.com', 
                                 'http://textcaptcha.com/register')));
                      
  $form['textcaptcha_api_key'] = array(
    '#type' => 'textfield',
    '#title' => 'Textcaptcha.com API key',
    '#description' => 'Your API key from textcaptcha.com',
    '#default_value' => variable_get('textcaptcha_api_key', ''),
  );
  
  return system_settings_form($form);
}

/**
 * Implementation of hook_captcha().
 */
function textcaptcha_captcha($op, $captcha_type='') {
  switch ($op) {
    case 'list' :
      return array('Text Captcha');
      break;
    case 'generate' :
      $result = array();
      if ($captcha_type == 'Text Captcha') {
        $textcaptcha = textcaptcha_get_captcha();
        $result['form']['captcha_response'] = array(
          '#type' => 'textfield',
          '#title' => $textcaptcha['question'],
          '#description' => t('Question text provided by !link',
                              array('!link' => l('textcaptcha.com', 'http://textcaptcha.com'))
                             ),
          '#size' => 50,
          '#maxlength' => 50,
          '#required' => TRUE,
        );
        $result['solution'] = serialize($textcaptcha['answers']);
        $result['captcha_validate'] = 'textcaptcha_captcha_validate';
        
        return $result;
      }
    break;
  }
}

/**
*  Retrieves CAPTCHA and possible answer list from the textcaptcha.com service
*/
function textcaptcha_get_captcha() {
  if (variable_get('textcaptcha_api_key', FALSE)) {
    $captcha = drupal_http_request('http://textcaptcha.com/api/'. 
          trim(variable_get('textcaptcha_api_key', '')));
    if ($captcha->code == '200' && $captcha->data) {
      $parser = drupal_xml_parser_create();
      $captcha_xml = array();
      xml_parse_into_struct($parser, $captcha->data, $captcha_xml);
      $answers = array();
      foreach ($captcha_xml as $element) {
        if ($element['tag'] == 'QUESTION' && $element['type'] == 'complete') {
          $question = $element['value'];
        }
        if ($element['tag'] == 'ANSWER' && $element['type'] == 'complete') {
          $answers[] = $element['value'];
        }
      }
      
    }
  }
  return array('question' => $question, 'answers' => $answers);
}

/**
*  Custom CAPTCHA validation callback.
*/
function textcaptcha_captcha_validate($solution, $response) {
  return (in_array(md5(drupal_strtolower(trim($response))), unserialize($solution)));
}